<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="Aspire.RabbitMQ.Client" />
		<PackageReference Include="Octokit.Webhooks.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FylumDeploy.ServiceDefaults\FylumDeploy.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
