<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!--Containerization-->
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <!--Aspire Orchestration-->
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.5.3" />
    <PackageVersion Include="Aspire.RabbitMQ.Client" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="13.5.3" />
    <!--Octokit GitHub interaction-->
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="Octokit.Webhooks.AspNetCore" Version="4.2.0" />
    <!--Hosting and Dependency Injection-->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <!--Networking-->
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.9.0" />
    <!--OpenTelemetry Service Defaults-->
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
  </ItemGroup>
</Project>