<Project Sdk="Aspire.AppHost.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>e3725f1f-b5ef-413a-b46a-711a8fbac1fd</UserSecretsId>
		<AspireUseCliBundle>true</AspireUseCliBundle>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Docker" />
		<PackageReference Include="Aspire.Hosting.RabbitMQ" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FylumDeploy.ComposeBuilder\FylumDeploy.ComposeBuilder.csproj" />
	  <ProjectReference Include="..\FylumDeploy.GitHubStatusUpdate\FylumDeploy.GitHubStatusUpdate.csproj" />
	  <ProjectReference Include="..\FylumDeploy.Webhook\FylumDeploy.Webhook.csproj" />
	</ItemGroup>

</Project>
