<Project Sdk="Aspire.AppHost.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>e3725f1f-b5ef-413a-b46a-711a8fbac1fd</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.Docker" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FylumDeploy.Webhook\FylumDeploy.Webhook.csproj" />
	</ItemGroup>

</Project>
