<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" />
    <PackageReference Include="Octokit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FylumDeploy.ServiceDefaults\FylumDeploy.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
